language: node_js
node_js:
  - "9.4"

branches:
  only:
    - master

before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g @angular/cli
  - npm install -g angular-cli-ghpages
  - npm install -g nyc
  - npm install -g codecov

script:
  - nyc npm test
  - ng build --prod --base-href "https://krahman.github.io/happy-cny-dragon/"
  - angular-cli-ghpages --repo=https://github.com/krahman/happy-cny-dragon.git --name="Khalilur Rahman" --email=khal.rahman@gmail.com

after_success:
  - codecov
