language: node_js
node_js:
  - "9.4"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - node_modules/karma/bin/karma start --config=karma.conf.js --single-run
  - ng build --prod
