language: node_js
node_js:
  - "9.4"

branches:
  only:
    - master

before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g @angular/cli
  - npm install -g nyc
  - npm install codecov -g

script:
  - nyc npm test
  - ng build --prod

after_success:
  - codecov
