# Test against the latest version of this Node.js version
environment:
  nodejs_version: "9"

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install --no-progress

test_script:
  - yarn ng -- build --prod --aot --no-progress
  - yarn test -- --single-run --no-progress

build: off
