# Test against the latest version of this Node.js version
environment:
  nodejs_version: "9"

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install --no-progress
  - npm install -g ync
  - npm install -g codecov
  - npm install -g angular-cli-ghpages

test_script:
  - nyc npm test
  - ng build --prod --base-href "https://krahman.github.io/happy-cny-dragon/"
  - ngh

build: off
